# Generated by Django 4.2.7 on 2023-12-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlist',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='description',
        ),
        migrations.AddField(
            model_name='eventlist',
            name='culture_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='donation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
