# Generated by Django 4.2.7 on 2023-12-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_eventlist_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
