# Generated by Django 4.2.7 on 2023-12-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_eventlist_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=264)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=64)),
            ],
        ),
    ]
