# Generated by Django 4.2.7 on 2023-12-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
