# Generated by Django 4.2.7 on 2023-12-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='about-us'),
        ),
    ]
