# Generated by Django 4.2.7 on 2023-12-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_aboutpage_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbouUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=264, null=True)),
                ('text', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='about-us-home')),
            ],
        ),
    ]
