# Generated by Django 4.2.7 on 2023-12-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_abouus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbouUs',
            new_name='AboutUs',
        ),
    ]
