# Generated by Django 4.2.7 on 2023-12-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_abouus_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=600)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial')),
            ],
        ),
    ]
