# Generated by Django 4.2.7 on 2023-12-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_testimonialsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=264)),
                ('subject', models.CharField(max_length=264)),
                ('message', models.TextField()),
            ],
        ),
    ]
