# Generated by Django 4.2.7 on 2023-12-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_range', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='donation')),
            ],
        ),
    ]
