# Generated by Django 4.2.7 on 2023-12-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_donatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatemodel',
            name='payment_email',
            field=models.EmailField(blank=True, max_length=264, null=True),
        ),
    ]
