# Generated by Django 4.2.7 on 2023-12-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_donatemodel_payment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatemodel',
            name='payment_email',
        ),
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.FileField(blank=True, null=True, upload_to='media_video')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='media_photo')),
                ('media_year', models.CharField(help_text='2021', max_length=50)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventlist')),
            ],
        ),
    ]
