# Generated by Django 4.2.7 on 2024-06-06 13:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlist',
            name='culture_program',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='schedule',
        ),
        migrations.AddField(
            model_name='eventlist',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
