# Generated by Django 4.2.7 on 2024-06-06 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_eventlist_culture_program_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlist',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='eventlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
